//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CopyGitLink {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CopyGitLink.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string CodeLensCopyLinkResultViewCopy {
            get {
                return ResourceManager.GetString("CodeLensCopyLinkResultViewCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait, we&apos;re generating a link....
        /// </summary>
        public static string CodeLensCopyLinkResultViewGeneratingLink {
            get {
                return ResourceManager.GetString("CodeLensCopyLinkResultViewGeneratingLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link is ready.
        /// </summary>
        public static string CodeLensCopyLinkResultViewLinkReady {
            get {
                return ResourceManager.GetString("CodeLensCopyLinkResultViewLinkReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string CreateGitRepositoryDialogOKButton {
            get {
                return ResourceManager.GetString("CreateGitRepositoryDialogOKButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Git link.
        /// </summary>
        public static string CreateGitRepositoryDialogTitle {
            get {
                return ResourceManager.GetString("CreateGitRepositoryDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigate to {0} and get started by adding your code to a new Git repository..
        /// </summary>
        public static string CreateGitRepositoryUserControlIndication {
            get {
                return ResourceManager.GetString("CreateGitRepositoryUserControlIndication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &gt; New &gt; Create a repository.
        /// </summary>
        public static string CreateGitRepositoryUserControlIndicationCommand {
            get {
                return ResourceManager.GetString("CreateGitRepositoryUserControlIndicationCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn more....
        /// </summary>
        public static string CreateGitRepositoryUserControlLearnMore {
            get {
                return ResourceManager.GetString("CreateGitRepositoryUserControlLearnMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get started by creating a Git repository.
        /// </summary>
        public static string CreateGitRepositoryUserControlTitle {
            get {
                return ResourceManager.GetString("CreateGitRepositoryUserControlTitle", resourceCulture);
            }
        }
    }
}
